# Generated by Django 3.2.7 on 2021-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unused_vacation_days',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
