# Generated by Django 3.2.7 on 2021-09-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleagues', '0002_auto_20210911_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile',
            new_name='phone',
        ),
    ]
