from django.urls import re_path
from colleagues import views

urlpatterns = [
	re_path(r'home/$', views.home, name='home'),
	re_path(r'signup/$', views.signup, name='signup'),
	re_path(r'login/$', views.login_, name='login'),
	re_path(r'logout/$', views.logout_, name='logout'),
	re_path(r'profile/$', views.my_account, name='profile'),
	re_path(r'set_benefits/(?P<pk>\d+)/$', views.set_benefits, name='set_benefits'),
	re_path(r'save_benefits/(?P<pk>\d+)/$', views.save_benefits, name='save_benefits'),
	re_path(r'upload_img/$', views.upload_img, name='upload_img'),
	# url(r'^register/$', views.register, name='register'),
	# url(r'^login/$', views.login_view, name='login'),
	# url(r'^logout/$', views.logout_view, name='logout'),
	# url(r'^cathegories/(?P<subcath_name>.+)/$', views.subcath, name='subcath'),
	# url(r'^cathegories/$', views.cathegories_view, name='cathegories'),
	# url(r'^cathegory_delete/$', views.cathegory_delete, name='cathegory_delete'),
	# url(r'^cathegory_rename/$', views.cathegory_rename, name='cathegory_rename'),
	# url(r'^cathegory_save/$', views.cathegory_save, name='cathegory_save'),
	# url(r'^cathegory_create/$', views.cathegory_create, name='cathegory_create'),
	# url(r'^printlog/$', views.printlog, name='printlog'),
	# url(r'^wares/itemshow/(?P<pk>\d+)/$', views.item_show, name='item_show'),
	# url(r'^wares/itemcreate/$', views.item_create, name='item_create'),
	# url(r'^wares/itemedit/(?P<pk>\d+)/$', views.item_edit, name='item_edit'),
	# url(r'^wares/itemdelete/$', views.item_delete, name='item_delete'),
	# url(r'^wares/itemlike/$', views.item_like, name='item_like'),
	# # url(r'^wares/itembuy/$', views.item_buy, name='item_buy'),
	# url(r'^shoppingcart/$', views.shopping_cart, name='shopping_cart'),
	# url(r'^shoppingcart/buy/$', views.buy, name='buy'),
	# url(r'^shipping/$', views.shipping, name='shipping'),
	# url(r'^shipping/sold/$', views.sold, name='sold'),
	# url(r'^wares/search/$', views.search, name='search'),
	# url(r'^wares/query/$', views.query, name='query'),
	# url(r'^ajax/change-qty/$', views.change_qty),
	# url(r'^ajax/discard/$', views.discard),
	# url(r'^ajax/add-to-sc/$', views.add_to_sc),
	# url(r'^wares/bought/$', views.ibought, name='bought'),
]